services:
  cache:
    image: redis:8.2-alpine
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    command: uvicorn vulnerability_tracking.main:app --reload --port 8000 --host 0.0.0.0
    env_file:
      - .env
    volumes:
      - ./vulnerability_tracking:/app/vulnerability_tracking
    ports:
      - 8000:8000
    depends_on:
      - cache
